### ISSUE TITLE
Add OAuth flow to auth

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/panoptes-javascript-client#13]
Would be super cool to have [the Mammoth Bats-style OAuth login](https://github.com/zooniverse/mammoth-bats/blob/master/app/stores/user-store.coffee#L76-L82) available as a method in the auth module

**Comment by rogerhutchings** [comment]
Also in [zooniverse/wellcome](https://github.com/zooniverse/wellcome), via

- 3b0ac15aea7f7052cebc92cfe0b8759d1ab445cd
- 1cd9b4389a2dc25a6b0d33e56a2008d03f72d2c3
- b2cac1f9bc3b693cc85a20bbd15d00d22e48634b

**Comment by eatyourgreens** [comment]
The wellcome code is mostly taken from Mammoth Bats :grinning: 

I think changing the client so that it can grab a token from `window.location`, if the POST to `/me` is forbidden, would work. The rest of that code just sets headers and stores the bearer token locally, which I think is already in the client.
